### ISSUE TITLE
Question on laggy neovim

### ISSUE THREAD

**Issue by aegatlin** [richin13/asdf-neovim#13]
Hey! thank you for the great plugin! I have a weird question.

Are you aware of any issues regarding sluggishness when using this plugin? [asdf-direnv](https://github.com/asdf-community/asdf-direnv) mentions how the shims can affect performance for some commands. I feel like I've noticed slower response times since I started using this plugin and wonder if its somehow calling out to the `nvim` shim multiple times during regular execution, or if it's something else. So this isn't really an issue with this plugin (because I can't yet determine if my issue is actually due to this plugin or something else), but, I was curious to get your thoughts on sluggishness. Do you use the asdf-direnv solution? Do you have any recommendations with regards to performance?

Thanks again for the plugin! :D

**Comment by richin13** [comment]
Hey, I'm so sorry for the slow response here.

I've been looking around and definitely what `asdf-direnv` mention in the README makes a lot sense. I haven't personally experienced slow response times when opening neovim or using it. I did some tests using the asdf-installed and a pre-built version I downloaded from [here](https://github.com/neovim/neovim/releases/tag/nightly) and indeed there's a difference when going through asdf's shims.

```
# asdf installed version (nightly)
Ψ time nvim -c "q"
nvim -c "q"  0.61s user 0.12s system 55% cpu 1.310 total
```

```
# Non-asdf pre-built
Ψ time ./nvim -c "q"
./nvim -c "q"  0.52s user 0.09s system 51% cpu 1.173 total
```

That regarding the startup time I think is something to expect, however when it comes to sluggishness within neovim (using it, navigating files, etc..)  I'm not sure asdf is too involved there, however I do have some settings in my `init.vim` in order to sort out some asdf particularities or just performance in general.

The first is setting is:

```
let g:python3_host_prog = $HOME . '/.asdf/shims/python3'
let g:python_host_prog  = $HOME . '/.asdf/shims/python2'
```

From `:h python3_host_prog`:

> Command to start Python 3 (executable, not directory). Setting this makes
startup faster. Useful for working with virtualenvs. Must be set before any
check for has("python3").

And the second setting being:

```
" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300
```

I had that comment for `updatetime`. The help page does not particularly mentions anything regarding user experience but it's worth a shot.

Anyway I'll be in the lookout for any slow response in my neovim instances and if I notice any I'll try to document what's going on! 

Thank you for putting this on my radar and again, sorry for being so slow to respond!

**Comment by aegatlin** [comment]
Hey @richin13, thank you for the reply. I ended up going with the asdf-direnv solution and afterwards the sluggishness was resolved. I have doubts that the asdf-direnv setup was actually the _reason_ the sluggishness went away. As you suggested, it doesn't seem like it would affect performance within nvim. For what it's worth, for any future readers here, I also have the `updatetime` nvim settings set quite low as well. I suspect the sluggishness was unrelated to asdf-nvim, but honestly I am still not sure. Anyways, I will close the issue. Thank you very much for your response. :)
